version: "3.8"
services:
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        ports:
            - 3306:3306
        volumes:
            - type: bind
              source: ./local/mysql/
              target: /var/lib/mysql