version: "3.8"
services:
    mysql:
        build: ./mysql
        environment:
            MYSQL_DATABASE: test
            MYSQL_USER: test
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        ports:
            - 3306:3306
        volumes:
            - type: bind
              source: ../spring-api/local/mysql/
              target: /var/lib/mysql
    tomcat:
        build: ./tomcat
        ports:
            - "8080:8080"
        volumes:
            - type: bind
              source: ../spring-api/build/libs/
              target: /usr/local/tomcat/webapps/
        depends_on:
            - mysql