spring:
  datasource:
    url: jdbc:mysql://${dbhost}:3306/${database}?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useOldAliasMetadataBehavior=true&SQL_SAFE_UPDATES=0
    username: ${dbusername}
    password: ENC(${dbpassword})
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      "ddl-auto": ${dbinit}
  jackson:
    default-property-inclusion: non-null
jasypt:
  encryptor:
    bean: encryptorBean
